name: "BIN \u2192 HEX exporter"
true:
  push:
    branches:
    - main
  pull_request: null
  workflow_dispatch: null
permissions:
  contents: read
jobs:
  export-hex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install deps
      run: 'python -m pip install --upgrade pip

        pip install intelhex pyyaml

        '
    - name: "Export BIN \u2192 HEX"
      run: "set -euo pipefail\nif [ -f scripts/export_bins_to_hex.py ]; then\n  python\
        \ scripts/export_bins_to_hex.py\nelse\n  echo \"scripts/export_bins_to_hex.py\
        \ missing\"\n  exit 1\nfi\n"
    - name: "Verify 1:1 (BIN \u2194 HEX)"
      run: "set -euo pipefail\nBIN_COUNT=$(find rawdata -type f -path '*/validated/*'\
        \ -iname '*.bin' | wc -l | tr -d ' ')\nHEX_COUNT=0\nif [ -d dist/deepseek/incoming\
        \ ]; then\n  HEX_COUNT=$(find dist/deepseek/incoming -type f -iname '*.hex'\
        \ | wc -l | tr -d ' ')\nfi\necho \"BIN_COUNT=$BIN_COUNT\"\necho \"HEX_COUNT=$HEX_COUNT\"\
        \nif [ \"$BIN_COUNT\" -eq 0 ]; then\n  echo \"No .bin files found under rawdata/**/validated/\
        \ \u2014 nothing to export.\"\n  exit 0\nfi\nif [ \"$HEX_COUNT\" -lt \"$BIN_COUNT\"\
        \ ]; then\n  echo \"::error ::Export produced fewer HEX files than BIN files\
        \ ($HEX_COUNT < $BIN_COUNT)\"\n  exit 1\nfi\n"
    - name: Upload HEX payload
      uses: actions/upload-artifact@v4
      with:
        name: deepseek-input-hex
        path: 'dist/deepseek/incoming/**/*.hex

          dist/deepseek/incoming/**/*.json

          dist/deepseek/incoming/manifest-hex.csv

          '
        if-no-files-found: ignore
'on':
  push:
    branches:
    - main
    - master
  pull_request: null
  workflow_dispatch: {}
