name: BIN → HEX exporter

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  export-hex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install intelhex pyyaml

      - name: Export BIN → HEX
        run: |
          set -euo pipefail
          if [ -f scripts/export_bins_to_hex.py ]; then
            python scripts/export_bins_to_hex.py
          else
            echo "scripts/export_bins_to_hex.py missing"
            exit 1
          fi

      - name: Verify 1:1 (BIN ↔ HEX)
        run: |
          set -euo pipefail
          BIN_COUNT=$(find rawdata -type f -path '*/validated/*' -iname '*.bin' | wc -l | tr -d ' ')
          HEX_COUNT=0
          if [ -d dist/deepseek/incoming ]; then
            HEX_COUNT=$(find dist/deepseek/incoming -type f -iname '*.hex' | wc -l | tr -d ' ')
          fi
          echo "BIN_COUNT=$BIN_COUNT"
          echo "HEX_COUNT=$HEX_COUNT"
          if [ "$BIN_COUNT" -eq 0 ]; then
            echo "No .bin files found under rawdata/**/validated/ — nothing to export."
            exit 0
          fi
          if [ "$HEX_COUNT" -lt "$BIN_COUNT" ]; then
            echo "::error ::Export produced fewer HEX files than BIN files ($HEX_COUNT < $BIN_COUNT)"
            exit 1
          fi

      - name: Upload HEX payload
        uses: actions/upload-artifact@v4
        with:
          name: deepseek-input-hex
          path: |
            dist/deepseek/incoming/**/*.hex
            dist/deepseek/incoming/**/*.json
            dist/deepseek/incoming/manifest-hex.csv
          if-no-files-found: ignore
